export const techs = [
  { value: "fullstack", label: "fullstack" },
  { value: "C#", label: "C#", expresion: /Python/gi },
  { value: "Python", label: "Python", color: "#5243AA" },
  { value: "red", label: "Red", color: "#FF5630" },
  { value: "orange", label: "Orange", color: "#FF8B00" },
  { value: "yellow", label: "Yellow", color: "#FFC400" },
  { value: "green", label: "Green", color: "#36B37E" },
  { value: "forest", label: "Forest", color: "#00875A" },
  { value: "slate", label: "Slate", color: "#253858" },
  { value: "silver", label: "Silver", color: "#666666" },
];

// export const techs = [
//   { value: "Python", label: "Python", expresion: /Python/gi },
//   { value: "Django", label: "Django", expresion: /Django/gi },
//   { value: "Flask", label: "Flask", expresion: /Flask/gi },
//   { value: "C++", label: "C++", expresion: /C\+\+/gi },
//   { value: "C#", label: "C#", expresion: /C#/gi },
//   { value: "C", label: "C", expresion: /^C\s/gi },
//   { value: "C", label: "C", expresion: /^C,\s/gi },
//   { value: "C", label: "C", expresion: /\sC\s/gi },
//   { value: "Golang", label: "Golang", expresion: /Golang/gi },
//   { value: "Java", label: "Java", expresion: /Java\s/gi },
//   { value: "Java", label: "Java", expresion: /Java,/gi },
//   { value: "Java", label: "Java", expresion: /\sJava$/gi },
//   { value: "Javascript", label: "Javascript", expresion: /Javascript/gi },
//   { value: "JS", label: "JS", expresion: /JS/gi },
//   { value: "NodeJs", label: "NodeJs", expresion: /NodeJs/gi },
//   { value: "React", label: "React", expresion: /React\s/gi },
//   { value: "React", label: "React", expresion: /React,/gi },
//   { value: "React", label: "React", expresion: /React$/gi },
//   { value: "React", label: "React", expresion: /\sReact/gi },
//   { value: "Vue", label: "Vue", expresion: /Vue/gi },
//   { value: "MySQL", label: "MySQL", expresion: /MySQL/gi },
//   { value: "SQL", label: "SQL", expresion: /\sSQL/gi },
//   { value: "NoSQL", label: "NoSQL", expresion: /NoSQL/gi },
//   { value: "MongoDB", label: "MongoDB", expresion: /MongoDb$/gi },
//   { value: "MongoDB", label: "MongoDB", expresion: /Mongo$/gi },
//   { value: "AWS", label: "AWS", expresion: /Aws/gi },
//   { value: "AWS", label: "AWS", expresion: /Amazon\sweb\sservices/gi },
//   { value: "Ruby", label: "Ruby", expresion: /Ruby\s,/gi },
//   { value: "Ruby", label: "Ruby", expresion: /Ruby,/gi },
//   { value: "Ruby", label: "Ruby", expresion: /Ruby$/gi },
//   { value: "HTML", label: "HTML", expresion: /HTML/gi },
//   { value: "CSS", label: "CSS", expresion: /CSS/gi },
//   { value: "Angular", label: "Angular", expresion: /Angular/gi },
//   { value: "Ruby on Rails", label: "Ruby on Rails", expresion: /Ruby\son\sRails/gi,},
//   { value: "Unity", label: "Unity", expresion: /Unity,/gi },
//   { value: "Unity", label: "Unity", expresion: /\sUnity\s/gi },
//   { value: "DataBases", label: "DataBases", expresion: /DataBases/gi },
//   { value: "Full Stack", label: "Full Stack", expresion: /Fullstack/gi },
//   { value: "Full Stack", label: "Full Stack", expresion: /Full-stack/gi },
//   { value: "Full Stack", label: "Full Stack", expresion: /Full\sstack/gi },
//   { value: "Frontend", label: "Frontend", expresion: /Frontend/gi },
//   { value: "Frontend", label: "Frontend", expresion: /Front-end/gi },
//   { value: "Frontend", label: "Frontend", expresion: /Front\send/gi },
//   { value: "Backend", label: "Backend", expresion: /Backend/gi },
//   { value: "Backend", label: "Backend", expresion: /Back-end/gi },
//   { value: "Backend", label: "Backend", expresion: /Back\send/gi },
//   { value: "DevOps", label: "DevOps", expresion: /Devops/gi },
// ];
