export const techs = [
  { value: "Python", label: "Python", expresion: /Python/gi },
  { value: "Django", label: "Django", expresion: /Django/gi },
  { value: "Flask", label: "Flask", expresion: /Flask/gi },
  { value: "C++", label: "C++", expresion: /C\+\+/gi },
  { value: "C#", label: "C#", expresion: /C#/gi },
  { value: "C", label: "C", expresion: /^C\s/gi },
  { value: "Golang", label: "Golang", expresion: /Golang/gi },
  { value: "Java", label: "Java", expresion: /Java\s/gi },
  { value: "Javascript", label: "Javascript", expresion: /Javascript/gi },
  { value: "JS", label: "JS", expresion: /JS/gi },
  { value: "NodeJs", label: "NodeJs", expresion: /NodeJs/gi },
  { value: "React", label: "React", expresion: /React\s/gi },
  { value: "Vue", label: "Vue", expresion: /Vue/gi },
  { value: "MySQL", label: "MySQL", expresion: /MySQL/gi },
  { value: "SQL", label: "SQL", expresion: /\sSQL/gi },
  { value: "NoSQL", label: "NoSQL", expresion: /NoSQL/gi },
  { value: "MongoDB", label: "MongoDB", expresion: /MongoDb$/gi },
  { value: "AWS", label: "AWS", expresion: /Aws/gi },
  { value: "Ruby", label: "Ruby", expresion: /Ruby\s,/gi },
  { value: "HTML", label: "HTML", expresion: /HTML/gi },
  { value: "CSS", label: "CSS", expresion: /CSS/gi },
  { value: "Angular", label: "Angular", expresion: /Angular/gi },
  { value: "Ruby on Rails", label: "Ruby on Rails", expresion: /Ruby\son\sRails/gi,},
  { value: "Unity", label: "Unity", expresion: /Unity,/gi },
  { value: "DataBases", label: "DataBases", expresion: /DataBases/gi },
  { value: "Full Stack", label: "Full Stack", expresion: /Fullstack/gi },
  { value: "Frontend", label: "Frontend", expresion: /Frontend/gi },
  { value: "Backend", label: "Backend", expresion: /Backend/gi },
  { value: "DevOps", label: "DevOps", expresion: /Devops/gi },
];
